# Generated by Django 3.0.5 on 2020-04-06 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationWorkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Organizations')),
                ('workers', models.ManyToManyField(to='main.Players')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationRanks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank_name', models.CharField(default='Rekrut', max_length=20)),
                ('visible_money', models.BooleanField(default=False)),
                ('visible_ranks', models.BooleanField(default=False)),
                ('visible_chat', models.BooleanField(default=False)),
                ('visible_cars', models.BooleanField(default=False)),
                ('visible_magazine', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Organizations')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Organization', to='main.Organizations')),
                ('ranks', models.ManyToManyField(related_name='Ranks', to='organization.OrganizationRanks')),
            ],
        ),
    ]
