# Generated by Django 3.0.5 on 2020-04-05 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0005_auto_20200404_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationWorkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Organizations')),
                ('workers', models.ManyToManyField(to='main.Players')),
            ],
        ),
    ]
