# Generated by Django 3.0.5 on 2020-04-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationranks',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
