# Generated by Django 3.0.5 on 2020-04-07 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationranks_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='Item', max_length=50)),
                ('item_category', models.CharField(blank=True, choices=[('Bronie', 'Narko')], max_length=50, null=True)),
            ],
        ),
    ]
