# Generated by Django 3.0.5 on 2020-04-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_organizations_ranks'),
        ('organization', '0003_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(blank=True, choices=[('Narkotyki', 'Narkotyki'), ('Bronie', 'Bronie'), ('Pozostałe', 'Pozostałe')], max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='item_name',
            field=models.CharField(default='item', max_length=50),
        ),
        migrations.CreateModel(
            name='PlayerItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Items')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Players')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Items')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Organizations')),
            ],
        ),
        migrations.AlterField(
            model_name='items',
            name='item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.ItemsCategory'),
        ),
    ]
