# Generated by Django 3.0.5 on 2020-04-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200407_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationitems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='organizationitems',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='playeritems',
            name='item',
        ),
        migrations.RemoveField(
            model_name='playeritems',
            name='player',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='ItemsCategory',
        ),
        migrations.DeleteModel(
            name='OrganizationItems',
        ),
        migrations.DeleteModel(
            name='PlayerItems',
        ),
    ]
