# Generated by Django 3.0.5 on 2020-04-08 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_players_items'),
        ('items', '0004_delete_organizationcars'),
        ('organization', '0005_auto_20200407_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationCars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cars_count', models.IntegerField(default=1)),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Cars')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Organizations')),
            ],
        ),
    ]
