# Generated by Django 3.0.5 on 2020-04-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organizationcars'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationranks',
            name='visible_phone',
            field=models.BooleanField(default=False),
        ),
    ]
