# Generated by Django 3.0.5 on 2020-04-08 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_delete_organizationitems'),
        ('main', '0010_auto_20200408_2234'),
        ('organization', '0007_organizationranks_visible_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField(default=1)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Items')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Organizations')),
            ],
        ),
    ]
