# Generated by Django 3.0.5 on 2020-04-09 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200408_2234'),
        ('organization', '0008_organizationitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_rank', to='organization.OrganizationRanks'),
        ),
        migrations.CreateModel(
            name='Invites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Organization')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Players')),
            ],
        ),
    ]
