# Generated by Django 3.0.5 on 2020-04-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20200410_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='default_rank',
        ),
    ]
