# Generated by Django 3.0.5 on 2020-04-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_organizations_default_rank'),
        ('organization', '0011_remove_organization_default_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invites',
            name='players',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Players'),
        ),
    ]
