# Generated by Django 3.0.5 on 2020-04-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20200410_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
