# Generated by Django 3.0.5 on 2020-04-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_delete_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationranks',
            name='rank_power',
            field=models.IntegerField(default=0),
        ),
    ]
