# Generated by Django 3.0.5 on 2020-04-12 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='if_pranie',
            field=models.IntegerField(blank=True, default=5000, null=True, validators=[django.core.validators.MaxValueValidator(30000), django.core.validators.MinValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='if_pranie_prowizja',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
