# Generated by Django 3.0.5 on 2020-04-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200413_0048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-order_type']},
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Oczekujący', 'Oczekujący'), ('W trakcie', 'W trakcie'), ('Do odbioru', 'Do odbioru'), ('Zakończone', 'Zakończone')], default='Oczekujący', max_length=50),
        ),
    ]
