# Generated by Django 3.0.5 on 2020-04-12 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200413_0107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'ordering': ['-created', '-order_type']},
        ),
    ]
