# Generated by Django 3.0.5 on 2020-04-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200413_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='received',
            field=models.BooleanField(default=False),
        ),
    ]
