# Generated by Django 3.0.5 on 2020-04-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20200408_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationCars',
        ),
    ]
