# Generated by Django 3.0.5 on 2020-04-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_delete_organizationcars'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='car_id',
            field=models.CharField(default='ABC 12345', max_length=9),
        ),
    ]
