# Generated by Django 3.0.5 on 2020-04-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizations',
            old_name='organization_money',
            new_name='money',
        ),
        migrations.RenameField(
            model_name='players',
            old_name='player_money',
            new_name='money',
        ),
    ]
