# Generated by Django 3.0.5 on 2020-04-06 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('main', '0002_auto_20200406_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='organization_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.OrganizationRanks'),
        ),
    ]
