# Generated by Django 3.0.5 on 2020-04-04 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200404_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Organizations'),
        ),
    ]
