# Generated by Django 3.0.5 on 2020-04-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200406_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ['-organization_level']},
        ),
    ]
