# Generated by Django 3.0.5 on 2020-04-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200404_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='money',
        ),
        migrations.AddField(
            model_name='players',
            name='money_bank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='players',
            name='money_portfel',
            field=models.IntegerField(default=0),
        ),
    ]
