# Generated by Django 3.0.5 on 2020-04-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationranks_admin'),
        ('main', '0004_auto_20200407_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='ranks',
            field=models.ManyToManyField(related_name='Rangi', to='organization.OrganizationRanks'),
        ),
    ]
