# Generated by Django 3.0.5 on 2020-04-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('main', '0005_organizations_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='items',
            field=models.ManyToManyField(blank=True, null=True, to='items.PlayerItems'),
        ),
    ]
