# Generated by Django 3.0.5 on 2020-04-07 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200408_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='players',
            name='items',
        ),
    ]
