# Generated by Django 3.0.5 on 2020-04-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_players_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='phone',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
