# Generated by Django 3.0.5 on 2020-04-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20200410_0056'),
        ('main', '0010_auto_20200408_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='organization.Invites'),
        ),
    ]
