# Generated by Django 3.0.5 on 2020-04-10 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_auto_20200410_0056'),
        ('main', '0012_auto_20200410_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='ranks',
            field=models.ManyToManyField(blank=True, null=True, related_name='Rangi', to='organization.OrganizationRanks'),
        ),
    ]
