# Generated by Django 3.0.5 on 2020-04-10 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_remove_organization_default_rank'),
        ('main', '0013_auto_20200410_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizations',
            name='default_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_rank', to='organization.OrganizationRanks'),
        ),
    ]
