# Generated by Django 3.0.5 on 2020-04-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_delete_organization'),
        ('main', '0015_auto_20200410_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='ranks',
            field=models.ManyToManyField(default=None, related_name='Rangi', to='organization.OrganizationRanks'),
        ),
    ]
