# Generated by Django 3.0.5 on 2020-04-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200410_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='phone',
            field=models.CharField(default='00-0000', max_length=7),
        ),
    ]
