# Generated by Django 3.0.5 on 2020-04-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200410_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizations',
            options={'ordering': ['-created']},
        ),
    ]
