# Generated by Django 3.0.5 on 2020-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_chatmessages'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='room_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
